Piston lifter prototype
RoboticsTeam4904/2018-Code pull request #9
Opened 2018-01-13 00:10 UTC by Codadillo

Code for the prototype of the support of the robot lifter.

2018-01-13 00:38 UTC, ajnadel requested changes
Get rid of the metadata junk.

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.liftPiston = new DoubleSolenoid (Port.Pneumatics.liftSupportOut, Port.Pneumatics.liftSupportIn);
Nit: extra space

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/RampLiftSupportOut.java
> +		// TODO Auto-generated method stub
Take this out.

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/RampLiftSupportIn.java
> +		// TODO Auto-generated method stub
Remove comment.

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/Lifter.java
> +		// TODO Auto-generated method stub
What's the default command?

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static int liftSupportOut = 0;
Make these `-1` if they're unknown.

2018-01-13 00:38 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/Lifter.java
> +		// TODO Auto-generated method stub
(Probably `Idle` command)

2018-01-14 18:19 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +
remove these extra added spaces

2018-01-26 19:27 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.liftPiston = new DoubleSolenoid(Port.Pneumatics.liftSupportOut, Port.Pneumatics.liftSupportIn);
Is there only one?

2018-01-26 19:30 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.liftPiston = new DoubleSolenoid(Port.Pneumatics.liftSupportOut, Port.Pneumatics.liftSupportIn);
Just initialize this in the `Lifter` constructor.

2018-02-17 19:03 UTC, NikhilSuresh24 requested changes

2018-02-17 19:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static int rightLifterSupportOut = -1;
Find out what these ports are

2018-02-17 19:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/LifterSet.java
> +		requires(lifter);
put requires before other things

2018-02-17 19:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +		RobotMap.Component.operatorStick.button4.onlyWhileHeld(new RunIf(
find out what these buttons should be

2018-12-15 01:02 UTC, merged